/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ChittiRouteImport } from './routes/chitti'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as ChittiIndexRouteImport } from './routes/chitti.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ChittiChittiIdRouteImport } from './routes/chitti.$chittiId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ChittiRoute = ChittiRouteImport.update({
  id: '/chitti',
  path: '/chitti',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const ChittiIndexRoute = ChittiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChittiRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)
const ChittiChittiIdRoute = ChittiChittiIdRouteImport.update({
  id: '/$chittiId',
  path: '/$chittiId',
  getParentRoute: () => ChittiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chitti': typeof ChittiRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/chitti/$chittiId': typeof ChittiChittiIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/chitti/': typeof ChittiIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/chitti/$chittiId': typeof ChittiChittiIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/chitti': typeof ChittiIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chitti': typeof ChittiRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/settings': typeof SettingsRoute
  '/chitti/$chittiId': typeof ChittiChittiIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/chitti/': typeof ChittiIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/chitti'
    | '/people'
    | '/settings'
    | '/chitti/$chittiId'
    | '/people/$personId'
    | '/chitti/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/settings'
    | '/chitti/$chittiId'
    | '/people/$personId'
    | '/chitti'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/chitti'
    | '/people'
    | '/settings'
    | '/chitti/$chittiId'
    | '/people/$personId'
    | '/chitti/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChittiRoute: typeof ChittiRouteWithChildren
  PeopleRoute: typeof PeopleRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chitti': {
      id: '/chitti'
      path: '/chitti'
      fullPath: '/chitti'
      preLoaderRoute: typeof ChittiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/chitti/': {
      id: '/chitti/'
      path: '/'
      fullPath: '/chitti/'
      preLoaderRoute: typeof ChittiIndexRouteImport
      parentRoute: typeof ChittiRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/chitti/$chittiId': {
      id: '/chitti/$chittiId'
      path: '/$chittiId'
      fullPath: '/chitti/$chittiId'
      preLoaderRoute: typeof ChittiChittiIdRouteImport
      parentRoute: typeof ChittiRoute
    }
  }
}

interface ChittiRouteChildren {
  ChittiChittiIdRoute: typeof ChittiChittiIdRoute
  ChittiIndexRoute: typeof ChittiIndexRoute
}

const ChittiRouteChildren: ChittiRouteChildren = {
  ChittiChittiIdRoute: ChittiChittiIdRoute,
  ChittiIndexRoute: ChittiIndexRoute,
}

const ChittiRouteWithChildren =
  ChittiRoute._addFileChildren(ChittiRouteChildren)

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChittiRoute: ChittiRouteWithChildren,
  PeopleRoute: PeopleRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
