import { getDb } from "@/lib/db";
import type { Person, DebtCategory, Transaction, Chitti, ChittiMonthlyPayment } from "@/lib/types";

export interface BackupData {
  app: "ledge";
  version: number;
  exportedAt: string;
  people: Person[];
  categories: DebtCategory[];
  transactions: Transaction[];
  chittis: Chitti[];
  chittiPayments: ChittiMonthlyPayment[];
}

export function validateAndMigrateBackup(data: any): BackupData {
  if (!data || typeof data !== "object") {
    throw new Error("Invalid backup: data is not an object.");
  }
  
  if (data.app !== "ledge") {
    throw new Error("Invalid backup: file was not generated by Ledge.");
  }

  const version = Number(data.version || 1);
  if (isNaN(version)) {
    throw new Error("Invalid backup: missing database version.");
  }

  // Basic lists initialization
  const people: Person[] = Array.isArray(data.people) ? data.people : [];
  const categories: DebtCategory[] = Array.isArray(data.categories) ? data.categories : [];
  const transactions: Transaction[] = Array.isArray(data.transactions) ? data.transactions : [];
  const chittis: Chitti[] = Array.isArray(data.chittis) ? data.chittis : [];
  const chittiPayments: ChittiMonthlyPayment[] = Array.isArray(data.chittiPayments) ? data.chittiPayments : [];

  // 1. Validate People
  for (const p of people) {
    if (!p.id || typeof p.id !== "string") throw new Error("Validation failed: Person missing string id.");
    if (!p.name || typeof p.name !== "string") throw new Error("Validation failed: Person missing name.");
    if (!Array.isArray(p.tags)) p.tags = [];
    if (!p.createdAt) p.createdAt = Date.now();
    if (!p.updatedAt) p.updatedAt = p.createdAt;
  }

  // 2. Validate Categories
  for (const c of categories) {
    if (!c.id || typeof c.id !== "string") throw new Error("Validation failed: Category missing string id.");
    if (!c.personId || typeof c.personId !== "string") throw new Error("Validation failed: Category missing personId.");
    if (!c.name || typeof c.name !== "string") throw new Error("Validation failed: Category missing name.");
    if (!c.createdAt) c.createdAt = Date.now();
    if (!c.updatedAt) c.updatedAt = c.createdAt;
  }

  // 3. Validate Transactions
  for (const t of transactions) {
    if (!t.id || typeof t.id !== "string") throw new Error("Validation failed: Transaction missing string id.");
    if (!t.personId || typeof t.personId !== "string") throw new Error("Validation failed: Transaction missing personId.");
    if (!t.categoryId || typeof t.categoryId !== "string") throw new Error("Validation failed: Transaction missing categoryId.");
    if (typeof t.amount !== "number" || isNaN(t.amount)) throw new Error("Validation failed: Transaction amount is invalid.");
    if (!t.type || !["lent", "borrowed", "repayment_in", "repayment_out"].includes(t.type)) {
      throw new Error(`Validation failed: Transaction has invalid type "${t.type}".`);
    }
    if (!t.date) t.date = Date.now();
    if (!t.createdAt) t.createdAt = t.date;
    if (!t.updatedAt) t.updatedAt = t.createdAt;
  }

  // 4. Validate Chittis (Migrating v1 if needed)
  for (const c of chittis) {
    if (!c.id || typeof c.id !== "string") throw new Error("Validation failed: Chitti missing string id.");
    if (!c.organizerId || typeof c.organizerId !== "string") throw new Error("Validation failed: Chitti missing organizerId.");
    if (typeof c.monthlyAmount !== "number" || isNaN(c.monthlyAmount)) throw new Error("Validation failed: Chitti monthlyAmount is invalid.");
    if (typeof c.numChits !== "number" || isNaN(c.numChits)) c.numChits = 1;
    if (!c.startDate) c.startDate = Date.now();
    if (typeof c.totalMonths !== "number" || isNaN(c.totalMonths)) c.totalMonths = 12;
    if (!c.status || !["active", "completed", "cancelled"].includes(c.status)) c.status = "active";
    if (c.availed === undefined) c.availed = false;
    if (!c.createdAt) c.createdAt = Date.now();
    if (!c.updatedAt) c.updatedAt = c.createdAt;

    // Migrate v1 legacy fields to availedSlots array if needed
    if (!c.availedSlots) {
      c.availedSlots = [
        {
          chitNumber: 1,
          availed: c.availed,
          availedDate: c.availedDate,
          availedAmount: c.availedAmount,
        },
      ];
    }
  }

  // 5. Validate Chitti Payments
  for (const cp of chittiPayments) {
    if (!cp.id || typeof cp.id !== "string") throw new Error("Validation failed: Chitti Payment missing string id.");
    if (!cp.chittiId || typeof cp.chittiId !== "string") throw new Error("Validation failed: Chitti Payment missing chittiId.");
    if (typeof cp.month !== "number" || isNaN(cp.month)) throw new Error("Validation failed: Chitti Payment month is invalid.");
    if (typeof cp.paidAmount !== "number" || isNaN(cp.paidAmount)) throw new Error("Validation failed: Chitti Payment paidAmount is invalid.");
    if (!cp.paidDate) cp.paidDate = Date.now();
    if (!cp.createdAt) cp.createdAt = cp.paidDate;
    if (!cp.updatedAt) cp.updatedAt = cp.createdAt;
  }

  return {
    app: "ledge",
    version: 2,
    exportedAt: new Date().toISOString(),
    people,
    categories,
    transactions,
    chittis,
    chittiPayments,
  };
}

export async function getDatabaseBackupPayload(): Promise<Omit<BackupData, "app" | "version" | "exportedAt">> {
  const db = getDb();
  const [people, categories, transactions, chittis, chittiPayments] = await Promise.all([
    db.people.toArray(),
    db.categories.toArray(),
    db.transactions.toArray(),
    db.chittis.toArray(),
    db.chittiPayments.toArray(),
  ]);
  return { people, categories, transactions, chittis, chittiPayments };
}

export async function importBackupPayload(payload: any) {
  const validated = validateAndMigrateBackup(payload);
  const db = getDb();
  
  await db.transaction(
    "rw",
    db.people,
    db.categories,
    db.transactions,
    db.chittis,
    db.chittiPayments,
    async () => {
      // Clear current database values
      await Promise.all([
        db.people.clear(),
        db.categories.clear(),
        db.transactions.clear(),
        db.chittis.clear(),
        db.chittiPayments.clear(),
      ]);

      // Bulk write values
      if (validated.people.length > 0) await db.people.bulkAdd(validated.people);
      if (validated.categories.length > 0) await db.categories.bulkAdd(validated.categories);
      if (validated.transactions.length > 0) await db.transactions.bulkAdd(validated.transactions);
      if (validated.chittis.length > 0) await db.chittis.bulkAdd(validated.chittis);
      if (validated.chittiPayments.length > 0) await db.chittiPayments.bulkAdd(validated.chittiPayments);
    }
  );
}

function escapeHTML(str: string): string {
  return str.replace(/[&<>'"]/g, (tag) => {
    return (
      {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        "'": "&#39;",
        '"': "&quot;",
      }[tag] || tag
    );
  });
}

export function downloadFile(content: BlobPart, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportToJSON() {
  const data = await getDatabaseBackupPayload();
  const payload = {
    app: "ledge",
    version: 2,
    exportedAt: new Date().toISOString(),
    ...data,
  };
  const jsonStr = JSON.stringify(payload, null, 2);
  downloadFile(jsonStr, `ledge-backup-${new Date().toISOString().slice(0, 10)}.json`, "application/json");
}

export async function exportToCSV() {
  const db = getDb();
  const [people, categories, transactions] = await Promise.all([
    db.people.toArray(),
    db.categories.toArray(),
    db.transactions.toArray(),
  ]);

  const peopleById = new Map(people.map((p) => [p.id, p]));
  const catsById = new Map(categories.map((c) => [c.id, c]));

  const headers = ["Date", "Person", "Category", "Type", "Amount", "Due Date", "Notes"];
  const rows = [
    headers,
    ...transactions.map((t) => [
      new Date(t.date).toISOString().slice(0, 10),
      peopleById.get(t.personId)?.name ?? "",
      catsById.get(t.categoryId)?.name ?? "",
      t.type,
      String(t.amount),
      t.dueDate ? new Date(t.dueDate).toISOString().slice(0, 10) : "",
      (t.notes ?? "").replace(/\n/g, " "),
    ]),
  ];

  const csvContent = rows
    .map((r) => r.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  downloadFile(csvContent, `ledge-transactions-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv");
}

export async function exportToExcel() {
  const db = getDb();
  const [people, categories, transactions] = await Promise.all([
    db.people.toArray(),
    db.categories.toArray(),
    db.transactions.toArray(),
  ]);

  const peopleById = new Map(people.map((p) => [p.id, p]));
  const catsById = new Map(categories.map((c) => [c.id, c]));

  const tableRows = transactions.map((t) => {
    const pName = peopleById.get(t.personId)?.name ?? "";
    const cName = catsById.get(t.categoryId)?.name ?? "";
    const dateStr = new Date(t.date).toISOString().slice(0, 10);
    const dueDateStr = t.dueDate ? new Date(t.dueDate).toISOString().slice(0, 10) : "";
    const notesStr = t.notes ?? "";

    return `
      <tr>
        <td>${dateStr}</td>
        <td>${escapeHTML(pName)}</td>
        <td>${escapeHTML(cName)}</td>
        <td>${t.type}</td>
        <td style="mso-number-format:'\\#,\\#\\#0\\.00'; text-align:right;">${t.amount}</td>
        <td>${dueDateStr}</td>
        <td>${escapeHTML(notesStr)}</td>
      </tr>
    `;
  }).join("");

  const excelTemplate = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <!--[if gte mso 9]>
      <xml>
        <x:ExcelWorkbook>
          <x:ExcelWorksheets>
            <x:ExcelWorksheet>
              <x:Name>Transactions</x:Name>
              <x:WorksheetOptions>
                <x:DisplayGridlines/>
              </x:WorksheetOptions>
            </x:ExcelWorksheet>
          </x:ExcelWorksheets>
        </x:ExcelWorkbook>
      </xml>
      <![endif]-->
      <style>
        th { background-color: #f2f2f2; font-weight: bold; border: 1px solid #cccccc; }
        td { border: 1px solid #cccccc; }
        table { border-collapse: collapse; }
      </style>
    </head>
    <body>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Person</th>
            <th>Category</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Due Date</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    </body>
    </html>
  `;

  downloadFile(
    excelTemplate,
    `ledge-transactions-${new Date().toISOString().slice(0, 10)}.xls`,
    "application/vnd.ms-excel"
  );
}
